DA: false
LPN: false
batchsize: 4
block: 4
color_jitter: false
data_dir_train: /home/chenquan/2023ACMworkshop/LPN-main/Dataset/University1652/train
data_dir_val: /home/chenquan/2023ACMworkshop/LPN-main/Dataset/University1652/test
decouple: false
dense_LPN: true
droprate: 0.75
erasing_p: 0
extra_Google: false
fp16: false
gpu_ids: '0'
h: 512
lr: 0.001
moving_avg: 1.0
ms: '1'
name: pretrained
nclasses: 701
pad: 10
pool: avg
resnet: true
resume: false
share: true
stride: 1
swin: false
train_all: false
use_NAS: false
use_dense: false
val_batchsize: 8
views: 2
w: 512
warm_epoch: 0
