python train_info_gem_denseLPN.py \
--name='model' \
--data_dir_train='/home/chenquan/2023ACMworkshop/LPN-main/Dataset/University1652/train' \
--data_dir_val='/home/chenquan/2023ACMworkshop/LPN-main/Dataset/University1652/test' \
--views=2 \
--batchsize=4 \
--droprate=0.75 \
--stride=1 \
--share \
--h=512 \
--w=512 \
--lr=0.001 \
--block=4 \
--resnet \
--dense_LPN \
--gpu_ids='0'
